### ISSUE TITLE
[builder] Unable to import module 'liblambda': /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /var/task/liblambda.so)

### ISSUE THREAD

**Issue by ilianaw** [ilianaw/rust-crowbar#20]
Amazon Linux 2017.09 ships with OpenSSL 1.0.2; Lambda is still on 1.0.1.

Making things more difficult, Python 3.6 was first released in Amazon Linux 2017.09, so there's not a build against OpenSSL 1.0.1, so we can't even downgrade `openssl-devel`.

Including `libcrypto.so.10` in the zip doesn't seem to help either; I think `/var/task` is lower precedence than system library paths in Lambda.

**Comment by ramn** [comment]
Any progress on this or any ideas?

**Comment by ilianaw** [comment]
Not currently.

If you're interested in spending some time to try and figure things out, [the lambci docker-lambda images](https://github.com/lambci/docker-lambda) might work okay (apparently [aws-sam-local](https://github.com/awslabs/aws-sam-local) uses them).

**Comment by ramn** [comment]
It works! Thanks. I just tried manually, perhaps that image can be used by crowbar.

**Comment by ramn** [comment]
I tried the build image w python3. I had to override crate python3-sys and set the feature to use python 3.4. On mobile now will share code later.

**Comment by ramn** [comment]
In the crowbar builder Dockerfile, I updated the FROM line to this:

FROM lambci/lambda:build-python3.6

And in my project, in Cargo.toml I added this:

python3-sys = { version = "0.1.3", features = ["python-3-4"] }

Where the feature "python-3-4" is the important part. However, with that feature enabled I can't build locally (on my mac, that is, not using the docker container). Perhaps that can be solved? Can we enable this feature only in the docker run?

**Comment by ramn** [comment]
It also works if I set `python3-sys = { version = "0.1.3", features = ["python-3-4"] }` in `rust-crowbar/Cargo.toml`.  Just need to be able to toggle this as a feature when running `cargo build`.

**Comment by ramn** [comment]
So I found a way of building locally with default python binding but override to the python3.4 when building in the crowbar builder docker container. I'll do a PR.

**Comment by ilianaw** [comment]
> python3-sys = { version = "0.1.3", features = ["python-3-4"] }

That is... super weird. Why is there even a python3.4 in that image...

**Comment by ramn** [comment]
Yes and I tried with python-3-5 which didn't work.

**Comment by softprops** [comment]
this is still an open issue what is the recommended workaround. I'm getting the same error. not being able to make https requests is a bit debilitating 

```bash
Unable to import module 'liblambda': /lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by /var/task/liblambda.so)

END RequestId: 420f016d-d7ed-11e7-bcec-c986dbdea94e
REPORT RequestId: 420f016d-d7ed-11e7-bcec-c986dbdea94e	Duration: 15.37 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 22 MB
```

**Comment by softprops** [comment]
the work around @ramn mentioned worked for me.

**Comment by ilianaw** [comment]
I *think* this is fixed now that we refer people to https://github.com/naftulikay/docker-crowbar?
