### ISSUE TITLE
Docker image needs a rebuild

### ISSUE THREAD

**Issue by kamek-pf** [ilianaw/rust-crowbar#5]
Hi !

I'm working on a project that does not compile against the current Docker image.
Some transient dependencies require compiler flags that were stabilized recently.

I see it hasn't been updated in 4 months. When you have a minute, could you rebuild the image and push on DockerHub ?

Nothing urgent, we can still rebuild locally :)

**Comment by ilianaw** [comment]
I'm going to rebuild it from master since the changes should still allow using the released crowbar, but if it breaks please let me know and I'll rebuild it from the 0.1.1 tag...
