### ISSUE TITLE
crowbar logo

### ISSUE THREAD

**Issue by softprops** [ilianaw/rust-crowbar#54]
I'd like to see crowbar have its on logo. It deserves one! I started experimenting with some ideas. let me know what you think @ilianaw . If you like any of these I can send a pull with a png + svg and a readme callout

1)
 here's a spin on the rust lang logo. replacing the R with an lambda character. I experimented a bit with various colors. AWS lambda tends toward orange which I'm not a super fan of by keeping a similar color may help draw some familiarity with the aws family crowbar situates itself with

![lambda-sprocket](https://user-images.githubusercontent.com/2242/47971977-46444c80-e065-11e8-8f9a-5013ee495f4d.png)

2) This one is the same but actually brings the word "crowbar" into it. I tried to pick a playful font but cause I crowbar is fun to use. I'm looking for something that kind of reflects that

![lambda-sproket-crowbar](https://user-images.githubusercontent.com/2242/47972008-9fac7b80-e065-11e8-8fb3-f9729f4ffda8.png)

3) This is the same sans color in rust's classic black 
![lambda-sproket-black](https://user-images.githubusercontent.com/2242/47972039-f44ff680-e065-11e8-9a40-9f644c335039.png)

4) this is an alternate of the above in "snake" green. some hint towards its python relation maybe. I just like colors but others may find this too much color :)

![lambda-sproket-crowbar-snake](https://user-images.githubusercontent.com/2242/47972065-2a8d7600-e066-11e8-822a-69df35853901.png)

5) same as above but crowbar to the side. potentially more efficient use of space in a readme

![lambda-sproket-crowbar-snakes-side](https://user-images.githubusercontent.com/2242/47972096-92dc5780-e066-11e8-8e11-7dbff59448a5.png)

6) just crowbar. 

![crowbar-snakes](https://user-images.githubusercontent.com/2242/47972101-a687be00-e066-11e8-86a6-f61f1a101742.png)

**Comment by softprops** [comment]
Simple is best. Thanks for the quick feedback

**Comment by softprops** [comment]
went with no. 1. pr here https://github.com/ilianaw/rust-crowbar/pull/55 :)

**Comment by ilianaw** [comment]
closed in #55
